/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_appsync_graphqlEndpoint": "https://fdd22jih25hohermvqyp6v3xxu.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-jjjfpm3rfnadbisvdt7zkdog6e",
    "aws_cognito_identity_pool_id": "us-east-2:1eb92aed-3617-4a55-991c-c1f078c256dd",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_9JRP32d0q",
    "aws_user_pools_web_client_id": "1a86ps8tkqae61vobag21ql3j4",
    "oauth": {},
    "aws_cognito_login_mechanisms": [
        "PREFERRED_USERNAME"
    ],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "logosbucket130759-dev",
    "aws_user_files_s3_bucket_region": "us-east-2"
};


export default awsmobile;
